import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin, Clock, Calendar, XCircle, CheckCircle } from "lucide-react";
import { usePendingAdvertisements } from '@/hooks/usePendingAdvertiments';
import { useServiceAdminApprovalMutation } from "@/hooks/useServiceAdminApproval";
export default function DashbordGroups() {
    const { ads, loading, error } = usePendingAdvertisements();
    const approvalMutation = useServiceAdminApprovalMutation();
    const handleApproval = (adId, status) => {
        approvalMutation.mutate({
            id: adId,
            approvalPayload: { adminApprovalStatus: status },
        });
    };
    console.log("ads", ads);
    if (loading)
        return _jsx("p", { className: "text-center text-gray-500 my-6 sm:my-10 text-base sm:text-lg", children: "Loading..." });
    if (error)
        return _jsx("p", { className: "text-center text-red-500 my-6 sm:my-10 text-base sm:text-lg", children: error });
    return (_jsx("div", { className: "space-y-4 sm:space-y-6 lg:space-y-8", children: ads && ads.length > 0 ? (ads.map((ad) => (_jsxs("div", { className: "bg-white p-4 sm:p-5 lg:p-6 rounded-xl sm:rounded-2xl shadow-sm max-w-6xl mx-auto my-3 sm:my-4 lg:my-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row justify-between items-start sm:items-center border-b pb-3 sm:pb-4 mb-3 sm:mb-4 gap-3 sm:gap-0", children: [_jsxs("div", { className: "flex-1 w-full", children: [_jsx("h2", { className: "text-base sm:text-lg font-semibold text-gray-700", children: "Advertisement Creator" }), _jsxs("div", { className: "flex items-center gap-2 sm:gap-3 mt-2 sm:mt-3", children: [_jsx("img", { src: ad?.user?.photo || "https://via.placeholder.com/80", alt: "creator", className: "w-10 h-10 sm:w-12 sm:h-12 lg:w-14 lg:h-14 rounded-full object-cover flex-shrink-0" }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h3", { className: "font-semibold text-sm sm:text-base text-gray-800 truncate", children: ad?.user?.fullName || "Unknown User" }), _jsx("p", { className: "text-xs sm:text-sm text-gray-500 truncate", children: ad?.user?.email }), _jsx("button", { className: "text-xs sm:text-sm text-blue-500 hover:underline mt-1", children: "Send Message" })] })] })] }), _jsxs("div", { className: "flex gap-2 sm:gap-3 flex-shrink-0", children: [_jsx("button", { className: "p-1.5 sm:p-2 bg-red-100 text-red-500 rounded-full hover:bg-red-200 transition disabled:opacity-50", onClick: () => handleApproval(ad._id, "rejected"), disabled: approvalMutation.isPending, children: _jsx(XCircle, { className: "w-5 h-5 sm:w-6 sm:h-6" }) }), _jsx("button", { className: "p-1.5 sm:p-2 bg-green-100 text-green-500 rounded-full hover:bg-green-200 transition disabled:opacity-50", onClick: () => handleApproval(ad._id, "approved"), disabled: approvalMutation.isPending, children: _jsx(CheckCircle, { className: "w-5 h-5 sm:w-6 sm:h-6" }) })] })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-lg sm:text-xl font-semibold mb-3 sm:mb-5 text-gray-800", children: "Advertisement Details" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 lg:gap-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-base sm:text-lg text-gray-800 mb-2 sm:mb-3", children: ad?.name }), _jsx("img", { src: ad?.image ||
                                                "https://images.unsplash.com/photo-1551836022-deb4988cc6c3", alt: "Ad", className: "rounded-lg sm:rounded-xl w-full h-40 sm:h-48 lg:h-56 object-cover mb-3 sm:mb-4" }), _jsxs("div", { className: "flex flex-wrap items-center gap-2 sm:gap-3 mb-3 text-xs sm:text-sm", children: [_jsxs("div", { className: "flex items-center bg-gray-100 px-2 sm:px-3 py-1 rounded-full", children: [_jsx(Calendar, { className: "w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2 text-green-600 flex-shrink-0" }), _jsx("span", { className: "truncate", children: new Date(ad?.extraDetails?.startDate).toLocaleDateString() })] }), _jsxs("div", { className: "flex items-center bg-gray-100 px-2 sm:px-3 py-1 rounded-full", children: [_jsx(Clock, { className: "w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2 text-green-600 flex-shrink-0" }), _jsx("span", { className: "truncate", children: new Date(ad?.extraDetails?.endDate).toLocaleDateString() })] }), _jsx("span", { className: "bg-green-600 text-white px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm capitalize", children: ad?.serviceType || "N/A" })] }), _jsxs("div", { className: "flex items-start gap-2 text-gray-600 mb-3 sm:mb-4", children: [_jsx(MapPin, { className: "w-4 h-4 sm:w-5 sm:h-5 text-green-600 flex-shrink-0 mt-0.5" }), _jsx("span", { className: "text-xs sm:text-sm break-words", children: ad?.location })] }), _jsxs("p", { className: "text-gray-600 text-xs sm:text-sm", children: ["Phone: ", _jsx("span", { className: "font-medium", children: ad?.phone })] })] }), _jsxs("div", { className: "text-gray-600 leading-relaxed space-y-3 sm:space-y-4", children: [_jsx("p", { className: "text-sm sm:text-base", children: ad?.description }), _jsxs("div", { className: "pt-3 sm:pt-4 border-t mt-3 sm:mt-4", children: [_jsxs("p", { className: "text-xs sm:text-sm mb-2", children: [_jsx("strong", { children: "Admin Approval:" }), " ", _jsx("span", { className: `px-2 py-1 rounded-full text-xs ${ad?.adminApprovalStatus === "approved"
                                                                ? "bg-green-100 text-green-700"
                                                                : ad?.adminApprovalStatus === "rejected"
                                                                    ? "bg-red-100 text-red-700"
                                                                    : "bg-yellow-100 text-yellow-700"}`, children: ad?.adminApprovalStatus })] }), _jsxs("p", { className: "text-xs sm:text-sm", children: [_jsx("strong", { children: "Payment Status:" }), " ", _jsx("span", { className: "capitalize", children: ad?.paymentStatus })] })] })] })] })] })] }, ad._id)))) : (_jsx("p", { className: "text-center text-gray-500 text-base sm:text-lg", children: "No advertisements found." })) }));
}
