import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
// A reusable, responsive "Not Found / Empty State" component with nice styling.
// Uses Tailwind for layout and framer-motion for a subtle entrance animation.
// Usage examples:
// <NotFound message="This course doesn't exist" />
// <NotFound title="No Results" message="We couldn't find matches for 'angular'" ctaLabel="Try again" onCta={() => retrySearch()} />
export default function NotFound({ title = "Not Found", message = "Sorry — we couldn't find what you're looking for.", ctaLabel = "Go home", onCta, secondaryLabel, secondaryOnClick, }) {
    return (_jsx(motion.div, { initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.35 }, className: "min-h-[60vh] flex items-center justify-center p-6 bg-gradient-to-b from-white via-gray-50 to-white", children: _jsx("div", { className: "max-w-xl w-full text-center bg-white/80 backdrop-blur-sm rounded-2xl shadow-2xl p-8 md:p-12 border border-gray-100", children: _jsxs("div", { className: "flex flex-col items-center gap-4", children: [_jsx("div", { className: "bg-red-50 border border-red-100 rounded-full p-4", children: _jsxs("svg", { className: "w-16 h-16 text-red-600", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", "aria-hidden": true, children: [_jsx("path", { d: "M11.25 7.5h1.5v6h-1.5v-6zM11.25 15.75h1.5v1.5h-1.5v-1.5z", fill: "currentColor" }), _jsx("path", { d: "M12 2C6.476 2 2 6.477 2 12s4.476 10 10 10 10-4.477 10-10S17.524 2 12 2zm0 18.5A8.5 8.5 0 1 1 12 3.5a8.5 8.5 0 0 1 0 17z", fill: "currentColor", opacity: "0.16" })] }) }), _jsx("h1", { className: "text-2xl md:text-3xl font-extrabold text-gray-900", children: title }), _jsx("p", { className: "text-gray-600 text-sm md:text-base", children: message }), _jsxs("div", { className: "mt-6 flex flex-col sm:flex-row gap-3 w-full justify-center", children: [onCta ? (_jsx("button", { onClick: onCta, className: "inline-flex items-center justify-center gap-2 px-5 py-2 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 text-white font-semibold shadow-md hover:brightness-95 transition", children: ctaLabel })) : (_jsx(Link, { to: "/", className: "inline-flex items-center justify-center gap-2 px-5 py-2 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 text-white font-semibold shadow-md hover:brightness-95 transition", children: ctaLabel })), secondaryLabel && (_jsx("button", { onClick: secondaryOnClick, className: "inline-flex items-center justify-center gap-2 px-5 py-2 rounded-full bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 transition", children: secondaryLabel }))] }), _jsx("div", { className: "mt-4 text-xs text-gray-400", children: "If you think this is a bug, contact support." })] }) }) }));
}
