import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, Outlet } from 'react-router-dom';
import logo from '@/assets/imgs/logo.png';
import { RiAdminLine } from "react-icons/ri";
import { TbReport } from "react-icons/tb";
import { RiAdvertisementLine } from "react-icons/ri";
import { VscSymbolEvent } from "react-icons/vsc";
import { MdOutlineProductionQuantityLimits } from "react-icons/md";
import { FaRegUser } from "react-icons/fa";
export default function AdminDashboard() {
    return (_jsxs("div", { className: "flex flex-col min-h-screen lg:flex-row", children: [_jsxs("div", { className: "w-full lg:w-64 bg-white border-r border-gray-200 p-4 sm:p-5 lg:p-6 flex flex-col", children: [_jsxs("div", { className: "flex items-center gap-2 mb-6 sm:mb-8", children: [_jsx("img", { src: logo, alt: "MCUS", className: "w-6 h-6 sm:w-8 sm:h-8" }), _jsx("h1", { className: "text-lg sm:text-xl font-semibold text-teal-700", children: "MCUS" })] }), _jsxs("nav", { className: "flex flex-row lg:flex-col gap-2 sm:gap-3 text-gray-600 overflow-x-auto lg:overflow-x-visible pb-2 lg:pb-0", children: [_jsxs(Link, { to: "/admin-dashboard/dashboard-anayltics", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(RiAdminLine, {}) }), _jsx("span", { className: "hidden sm:inline", children: "Admin Dashboard" }), _jsx("span", { className: "sm:hidden", children: "Dashboard" })] }), _jsxs(Link, { to: "/admin-dashboard/dashbord-contactus", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(TbReport, {}) }), "Reports"] }), _jsxs(Link, { to: "/admin-dashboard/dashboard-groups", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(RiAdvertisementLine, {}) }), _jsx("span", { className: "hidden sm:inline", children: "Advertisment" }), _jsx("span", { className: "sm:hidden", children: "Ads" })] }), _jsxs(Link, { to: "/admin-dashboard/dashboard-events", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(VscSymbolEvent, {}) }), "Events"] }), _jsxs(Link, { to: "/admin-dashboard/dashbord-products", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(MdOutlineProductionQuantityLimits, {}) }), "Products"] }), _jsxs(Link, { to: "/admin-dashboard/dashbord-users", className: `text-teal-600 flex items-center gap-2 sm:gap-4 text-sm sm:text-base p-2 rounded hover:bg-orange-100 whitespace-nowrap`, children: [_jsx("span", { className: "text-base sm:text-lg", children: _jsx(FaRegUser, {}) }), "Users"] })] })] }), _jsx("div", { className: "flex-1 bg-gray-50 p-3 sm:p-4 md:p-5 lg:p-6 overflow-auto", children: _jsx(Outlet, {}) })] }));
}
